# [ Numpy ]

In [1]:
import numpy as np
np.array([1,5,7,6]) # 1d tensor (0d : scalar, 2d : matrix)
# row/column : 2d tensor

array([1, 5, 7, 6])

In [2]:
np.array([1.25, 1, 5, 7]) # array는 data type이 같아야함. 
# 모두 float형태로 반환함. 

array([1.25, 1.  , 5.  , 7.  ])

### 난수 생성

In [3]:
# 0을 5개
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [4]:
np.ones([2,3], dtype=float) # row 2, column 3 2D tensor

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.arange(0, 10, 2) # 0포함, 10불포함, 2간격

array([0, 2, 4, 6, 8])

In [6]:
np.linspace(0, 1, 5) # 0과 1을 5등분

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.random.seed(12) # seed를 고정해야지 같은 결과가 나옴
np.random.random((3,3)) # 3*3 U(0, 1) 균일분포 난수 생성

array([[0.15416284, 0.7400497 , 0.26331502],
       [0.53373939, 0.01457496, 0.91874701],
       [0.90071485, 0.03342143, 0.95694934]])

In [9]:
np.random.normal(0, 1, (3,3)) # 3*3 N(0, 1) 정규분포 난수 생성

array([[-0.42069204, -0.7060276 ,  0.58535808],
       [ 0.13978644,  2.73781428,  1.11674795],
       [ 1.57453814, -0.08586679,  0.47673663]])

In [10]:
np.random.randint(0, 10, (3,3)) # 3*3 정수(0~9사이) 난수 생성

array([[9, 0, 0],
       [9, 8, 9],
       [6, 1, 8]])

In [11]:
# np.random.RandomState() 클래스를 rg 객체화
rg = np.random.RandomState(40) # 랜덤스테이트 객체 저장
# np.random 라이브러리 밑에 RandomState 클래스가 있음. 
rg.normal(0, 1, (3,3)) 

array([[-0.6075477 , -0.12613641, -0.68460636],
       [ 0.92871475, -1.84440103, -0.46700242],
       [ 2.29249034,  0.48881005,  0.71026699]])

In [29]:
## array의 객체화
np.random.seed(1)
x = np.random.randint(10, size=(2,3,4)) # 3D tensor(맨 앞은 sample의 숫자)
print(x);print(x.ndim);print(x.shape);print(x.size)
# ndim : 3차원, size : 24(element 개수)

xx = x.flatten();print(xx) # flatten : 차원에 관계 없이 쭉 1차원으로 펼침

[[[5 8 9 5]
  [0 0 1 7]
  [6 9 2 4]]

 [[5 2 4 2]
  [4 7 7 9]
  [1 7 0 6]]]
3
(2, 3, 4)
24
[5 8 9 5 0 0 1 7 6 9 2 4 5 2 4 2 4 7 7 9 1 7 0 6]


### array 접근과 편집

In [31]:
# array 접근
x = np.array([0,3,5,2,4,6])
print(x[1]);print(x[1:3]);print(x[1:-2]) # 1부터 끝에서 두번째-1 까지

3
[3 5]
[3 5 2]


In [37]:
# x[start : stop : step] 형식 (2D)
# x[start : stop : step, start : stop : step] (3D)

print(x)
print(x[::2]) # start, stop은 디폴트(처음부터 끝까지), step만 2칸씩 띄기
print(x[:2]) # start, step은 디폴트. 2번째전에서 stop
print(x[::-1]) # 역순으로 읽어줌
print(x[5::-2]) # 5번째부터 시작해 역순으로 2칸씩 띄어서 출력 

[0 3 5 2 4 6]
[0 5 4]
[0 3]
[6 4 2 5 3 0]
[6 2 3]


In [46]:
# 2D tensor
x = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
print(x);print(x[:2, :2])
print(x[:,0]) # 첫째 열
print(x[0, :]) # 첫째 행

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[1 4 7]
[1 2 3]
[1 2 3]


In [48]:
x[0] # 자동으로 행을 표시함

array([1, 2, 3])

In [52]:
print(x[1,2]) # 첫번째의 2번째 원소(list와 다름. list는 x[1][2]로 같은 작업 수행)
print(x[1][2]) 

6
6


In [57]:
x[0,0] = 99 # (0,0) element를 99로 바꿈
x

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [58]:
x1 = x[:2, :2] # 2행, 2열만 선택
x1 

array([[99,  2],
       [ 4,  5]])

In [59]:
x1[0,1] = 99;x1 # (0,1) 원소를 99로 바꿈

array([[99, 99],
       [ 4,  5]])

In [60]:
x # x1을 수정하면 x에도 반영이 됨. x1은 x의 객체에 불과할 뿐임. 
# x1이 바뀌면 원래 왔던 x도 바뀜을 유의하자!!

array([[99, 99,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

객체화를 함으로써 객체화된 것을 바꾸면 원래것들도 바뀜을 유의하자!

In [64]:
# x를 바뀌지 않게 하는 법 : copy()를 이용함
x1_copy = x[:2, :2].copy()
x1_copy[0,0] = 1000
print(x1_copy);print(x1) # x1의 변화가 x에 영향을 주지 않는 모습!

[[1000   99]
 [   4    5]]
[[99 99]
 [ 4  5]]


In [25]:
# array 편집
x1 = x[:, np.newaxis] # 2D(column vector)로 바뀜(axis=1)
print(x1)
x5 = x[np.newaxis, :];print(x5) # 2D row vector로 바뀜(axis=0)
x2 = x.reshape(6,1)
print(x2)
x3 = np.reshape(x, (6, 1))
print(x3)
x4 = x3.flatten();print(x4) # flatten : 1차원으로 펼쳐줌. 

[[0]
 [3]
 [5]
 [2]
 [4]
 [6]]
[[0 3 5 2 4 6]]
[[0]
 [3]
 [5]
 [2]
 [4]
 [6]]
[[0]
 [3]
 [5]
 [2]
 [4]
 [6]]
[0 3 5 2 4 6]


### 차원변경

In [130]:
# reshape 이용
x = np.array([1,2,3]);print(x);print(x.shape)
x.reshape((1,3));print(x);print(x.shape)
x.reshape((3,1));print(x);print(x.shape) 
# but reshape만으로는 차원이 변하지 않음

# row, column 벡터는 2D tensor임을 주의하자!
# 1차원 > 2차원 array : np.newaxis 사용
x1 = x[np.newaxis, :];print(x1) # 2차원 행벡터화([]가 하나 더 생김)
x2 = x[:, np.newaxis];print(x2) # 2차원 열벡터화

[1 2 3]
(3,)
[1 2 3]
(3,)
[1 2 3]
(3,)
[[1 2 3]]
[[1]
 [2]
 [3]]


In [74]:
x = np.random.randint(10, size=(3,3,4));print(x) # 3d tensor 
# 3개의 observation, 3*4는 픽셀. 

# size 변경 : reshape(sample과 픽셀 사이즈(곱)를 맞춰줘야함)
x1 = x.reshape((3,12));print(x1) 
x2 = x.reshape((-1, 12));print(x2) # 맞춰주기 귀찮을때는 -1. 알아서 해줌. 

[[[4 7 7 4]
  [9 0 2 0]
  [7 1 7 9]]

 [[8 4 0 1]
  [9 8 2 3]
  [1 2 7 2]]

 [[6 0 9 2]
  [6 6 2 7]
  [7 0 6 5]]]
[[4 7 7 4 9 0 2 0 7 1 7 9]
 [8 4 0 1 9 8 2 3 1 2 7 2]
 [6 0 9 2 6 6 2 7 7 0 6 5]]
[[4 7 7 4 9 0 2 0 7 1 7 9]
 [8 4 0 1 9 8 2 3 1 2 7 2]
 [6 0 9 2 6 6 2 7 7 0 6 5]]


### 분할

In [75]:
x = [1,2,3,4,5,6,7,8]
x1, x2, x3 = np.split(x, [2,6]);print(x1, x2, x3)
# [2,6] : '0~1 / 2~5 / 6~ 나머지'로 쪼개라는 뜻

[1 2] [3 4 5 6] [7 8]


In [76]:
# 분할하여 저장한 변수의 변경은 원래 x에 반영되지 않음. 
x1[0] = 100;print(x1)
print(x)

[100   2]
[1, 2, 3, 4, 5, 6, 7, 8]


In [77]:
x = np.random.random((4,4));print(x)

[[0.61714491 0.3266449  0.5270581  0.8859421 ]
 [0.35726976 0.90853515 0.62336012 0.01582124]
 [0.92943723 0.69089692 0.99732285 0.17234051]
 [0.13713575 0.93259546 0.69681816 0.06600017]]


In [84]:
# vsplit : 가로분할
x1, x2 = np.vsplit(x, [2]) # 숫자는 첫번째 분할을 뭘로 할 것인가? 
print(x1)
print('-'*60)
print(x2)

[[0.61714491 0.3266449  0.5270581  0.8859421 ]
 [0.35726976 0.90853515 0.62336012 0.01582124]]
------------------------------------------------------------
[[0.92943723 0.69089692 0.99732285 0.17234051]
 [0.13713575 0.93259546 0.69681816 0.06600017]]


In [82]:
# hsplit : 세로분할
y1, y2 = np.hsplit(x, [2])
print(y1)
print('-' * 60)
print(y2)

[[0.61714491 0.3266449 ]
 [0.35726976 0.90853515]
 [0.92943723 0.69089692]
 [0.13713575 0.93259546]]
------------------------------------------------------------
[[0.5270581  0.8859421 ]
 [0.62336012 0.01582124]
 [0.99732285 0.17234051]
 [0.69681816 0.06600017]]


### 덧붙이기

In [85]:
# concatenate : observation 을 늘린다. 
x = np.array([1,2])
y = np.array([2,3])
z = np.array([4,5])
np.concatenate([x,y,z]) # 연결지을 array는 꼭 대괄호[] 로 묶어준다!

array([1, 2, 2, 3, 4, 5])

In [91]:
xx = np.array([[1,2,3], [4,5,6]])
yy = np.array([[2,4,6], [6,7,8]])
print(xx);print(yy)

zz = np.concatenate([xx, yy], axis=1);print(zz) # axis=1 : 칼럼으로 연결
zz = np.concatenate([xx, yy], axis=0);print(zz) # axis=0 : 행으로 연결

[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [6 7 8]]
[[1 2 3 2 4 6]
 [4 5 6 6 7 8]]
[[1 2 3]
 [4 5 6]
 [2 4 6]
 [6 7 8]]


In [94]:
# vstack : 세로로 위에 쌓기. 
# np.concatenate([aa.reshape((1,3)), xx])과 결과 동일

aa = np.array([55,66,77])
np.vstack([aa, xx])

array([[55, 66, 77],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [105]:
# hstack : 가로로 옆에 쌓기
ww = np.array([[100, 200]]);print(ww);print(ww.shape) # 이렇게 붙이면 왠지 모르게 안붙음
np.hstack([ww,xx])

[[100 200]]
(1, 2)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

In [107]:
# 붙이는 array 지정에 유의하기!
ww = np.array([[100], [200]]);print(ww);print(ww.shape)
np.hstack([ww, xx])

[[100]
 [200]]
(2, 1)


array([[100,   1,   2,   3],
       [200,   4,   5,   6]])

### 연산

In [114]:
# array element 마다 연산이 들어감(broadcasting)
x = np.array([1,2,3,4])
print(x+3)
print(x/3)
print(x**3)

print(np.exp(x))
print(np.power(3, x)) # 3의 x승
print(np.log(x))
print(np.log2(x))

[4 5 6 7]
[0.33333333 0.66666667 1.         1.33333333]
[ 1  8 27 64]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 3  9 27 81]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]


In [118]:
# 행렬 단위 연산
M = np.ones((3,3));print(M)
M1 = M + 1;print(M1)

a = np.array([1,2,3]) # 행단위로 한 행씩 더한다!~!!!
M2 = M + a ; print(M2) 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [135]:
a = np.arange(3);print(a);print(a.shape)
b = np.arange(3)
b = b[:, np.newaxis];print(b);print(b.shape)

# 차원이 다른 두 array 연산 (a = 1차원, b = 2차원)
# 차원이 안맞으므로 0,1,2 행 3개, 열 3개를 임의로 만들어서 연산한다
print(a+b)

[0 1 2]
(3,)
[[0]
 [1]
 [2]]
(3, 1)
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [136]:
# 기초통계량 계산
np.random.seed(13)
x = np.random.randint(10, size=(3,4));x

array([[2, 0, 0, 6],
       [2, 4, 9, 3],
       [4, 2, 6, 5]])

In [140]:
print(np.sum(x))
# axis 주의하기!!

print(np.min(x, axis=1)) # 각 행의 최소값(row 별로)
print(np.mean(x, axis=0)) # 각 열의 평균(column 별로)
print(np.std(x, axis=0)) # 각 열의 표준편차(column 별로)

43
[0 2 2]
[2.66666667 2.         5.         4.66666667]
[0.94280904 1.63299316 3.74165739 1.24721913]


In [142]:
x_std = (x - np.mean(x, axis=0)) /np.std(x, axis=0) # 표준화
print(np.sum(x_std, axis=0)) # 왜더하는지는 잘 모르겠네~~~

[ 4.44089210e-16  0.00000000e+00  1.11022302e-16 -7.77156117e-16]


### 논리인덱싱(Boolean indexing), 순서정렬(Sorting)

In [143]:
x = np.array([[1,2,3,4], [5,6,7,8]]);print(x) # 2D tensor

[[1 2 3 4]
 [5 6 7 8]]


In [146]:
print(x>=5)
print(np.sum(x>=5)) # true에 해당하는게 1로 더해짐
print(np.sum(x>=5, axis=1)) # 각 행별로 연산(첫행은 0개, 둘째행은 4개)

[[False False False False]
 [ True  True  True  True]]
4
[0 4]


In [147]:
print(np.any(x>100)) # any : 100보다 큰게 하나라도 있는가? False
print(np.all(x<7, axis=0)) # 각 열별로 모두 7보다 작은가? 
print(np.all(x==100)) # 모두 x가 100인가?

False
[ True  True False False]
False


In [151]:
# 논리인덱싱
x = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12], [13, 14, 15, 16]]);print(x)
y = np.array([1,0,1,0]);print(y)
print('-'*50)
print(x[y==0, :]) # y==0인 자리의 열만 출력하기
print('-'*50)
print(x[:, y==0]) # y==0인 자리의 행만 출력하기

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 0 1 0]
--------------------------------------------------
[[ 5  6  7  8]
 [13 14 15 16]]
--------------------------------------------------
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [155]:
# array를 활용한 인덱싱
# 뽑고싶은 인덱스를 array로 지정한다!

x = np.array([11,12,13,14,15,16,17,18,19]);print(x) # 1차원 array
print('-'*50)

ind1 = np.array([2,3,4]) # 1차원 array 중 2,3,4번째만 출력(0부터 시작됨!)
x1 = x[ind1]
print(x1)
print('-'*50)

# 2번째, 1번째, 3번째 등에 해당하는 원소로 2차원 array 만들기
# 1차원 array를 2차원 array로 바꿀 수 있음! 
ind2 = np.array([[2,1,3], [5,2,7]]) 
x2 = x[ind2]
print(x2)

[11 12 13 14 15 16 17 18 19]
--------------------------------------------------
[13 14 15]
--------------------------------------------------
[[13 12 14]
 [16 13 18]]


In [165]:
x = np.arange(12).reshape((3,4));print(x)
ind = np.array([1,0]) # 이렇게 하면 몇행 몇행 이렇게 골라서 차례로 출력해줌. 
x1 = x[ind];x1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[4, 5, 6, 7],
       [0, 1, 2, 3]])

In [168]:
ind2 = np.array([1,3])
xx = x[:, -ind2];print(xx) # (역순으로 첫번째, 세번째 행이 출력됨!)
# -ind : not index. 1,3번째(0부터 세기) 컬럼 제외(근데 이렇게하면 위치가안맞는데 교수님이 이렇게설명함)

[[ 3  1]
 [ 7  5]
 [11  9]]


In [169]:
-ind2 # 전체 마이너스가 붙어서 나옴. 

array([-1, -3])

In [177]:
y1 = np.array([1,2,2]);print(y1)
y2 = np.array([2,0,1]);print(y2)
print(y1[:, np.newaxis]) # 열벡터로 만듦
print('-'*50)
print(x)

[1 2 2]
[2 0 1]
[[1]
 [2]
 [2]]
--------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [173]:
# y1으로 우선 행 선택하고, y2 위치에 해당하는 요소를 고른다. 
print(x[y1, y2])

[6 8 9]


In [175]:
print(x[y1[:, np.newaxis], y2]) # broadcasting
# 아니 이거 어칸다는거야??

[[ 6  4  5]
 [10  8  9]
 [10  8  9]]


In [178]:
[y1[:, np.newaxis], y2] 

[array([[1],
        [2],
        [2]]),
 array([2, 0, 1])]

In [179]:
## 순서정렬
# sort : 오름차순 정렬
x = np.array([2,4,3,1,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [182]:
# argsort : 순서대로 인덱스 반환
ind = np.argsort(x)
ind

array([3, 0, 2, 1, 4], dtype=int64)

In [188]:
x = np.random.randint(1, 10, size=(2,3,4));print(x)
x1 = x[:, -1, :];print(x1)
# -1이니까 가장 끝에있는 row들 전체 출력

[[[1 9 3 4]
  [4 1 2 9]
  [1 6 1 6]]

 [[5 9 1 7]
  [2 5 2 8]
  [2 9 9 9]]]
[[1 6 1 6]
 [2 9 9 9]]


In [189]:
x[1, -1, :] # 1번째 샘플 가장 끝에있는 row 출력

array([2, 9, 9, 9])

In [190]:
x[1, -1, 1] # 1번째 샘플 가장 끝에있는 row의 1번째 element 출력

9