# 과제 5

Iris 데이터에 logisticregression을 적용하되, multi_class=’ovr’과 ‘multinomial’을 적용한 후, 추정된 sigmoid함수와 softmax 함수를 제시하고 해석하라. (intercept와 coefficient 제시 후 해석)

In [1]:
import seaborn as sns 
data = sns.load_dataset('iris')  

from sklearn.preprocessing import LabelEncoder  # 인코딩   
classle = LabelEncoder()
data['species'] = classle.fit_transform(data['species'].values) 

X = data.drop('species', axis=1) 
y = data['species']

# 트테분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                    random_state=1, stratify=y)

In [2]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(105, 4) (45, 4) (105,) (45,)


In [3]:
data

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [4]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [5]:
train_col = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [6]:
# 0, 1인것 먼저 적합(1일확률)
data_1 = data.query('species!=2')

In [7]:
data_1

sepal_length  sepal_width  petal_length  petal_width  species
0            5.1          3.5           1.4          0.2        0
1            4.9          3.0           1.4          0.2        0
2            4.7          3.2           1.3          0.2        0
3            4.6          3.1           1.5          0.2        0
4            5.0          3.6           1.4          0.2        0
..           ...          ...           ...          ...      ...
95           5.7          3.0           4.2          1.2        1
96           5.7          2.9           4.2          1.3        1
97           6.2          2.9           4.3          1.3        1
98           5.1          2.5           3.0          1.1        1
99           5.7          2.8           4.1          1.3        1

[100 rows x 5 columns]

In [8]:
# from sklearn.linear_model import LogisticRegression
# import statsmodels.api as sm

# model = sm.Logit(data_1['species'], data_1[train_col])
# model.fit()

## Ovr - sigmoid
- OVR(=OVA, 일대다 전략) : One-Versus-Rest, One-Versus-All
- 한 분류에 대한 다른 분류의 이진 분류를 클래스 개수만큼 반복함. 

In [9]:
# Logistic regression
from sklearn.linear_model import LogisticRegression
Logit = LogisticRegression(C=1e2, random_state=1, multi_class='ovr') 
model=Logit.fit(X_train, y_train)
y_train_pred = Logit.predict(X_train)
y_test_pred = Logit.predict(X_test)

In [10]:
print(X_train.shape, X_test.shape)

(105, 4) (45, 4)


In [11]:
data['species'].value_counts()

2    50
1    50
0    50
Name: species, dtype: int64

In [12]:
# 특정 분류 하나만 구분하는 분류별 회귀식 3개
# 첫째 : 0만 구분하게함, 둘째 : 1만 구분하게함, 셋째 : 2만 구분하게함. 
model.coef_

array([[-0.76671984,  2.09831221, -4.68649463, -1.9094582 ],
       [-1.55950151, -2.15532289,  1.99096135, -2.96098118],
       [-0.79884463, -4.12128048,  6.23015952,  9.97751475]])

In [13]:
model.intercept_

array([ 11.74134616,  10.71605225, -30.65341967])

In [68]:
X_test.head()

sepal_length  sepal_width  petal_length  petal_width
148           6.2          3.4           5.4          2.3
5             5.4          3.9           1.7          0.4
6             4.6          3.4           1.4          0.3
106           4.9          2.5           4.5          1.7
75            6.6          3.0           4.4          1.4

In [69]:
x11 = np.array(X_test['sepal_length'].tolist())
x22 = np.array(X_test['sepal_width'].tolist())
x33 = np.array(X_test['petal_length'].tolist())
x44 = np.array(X_test['petal_width'].tolist())

In [14]:
# 회귀 방정식 생성
def reg(x1, x2, x3, x4):
    y1 = 11.74134616 -0.76671984*x1 + 2.09831221*x2 -4.68649463*x3 -1.9094582 *x4
    y2 = 10.71605225 -1.55950151*x1 -2.15532289*x2 +1.99096135*x3 -2.96098118*x4
    y3 = -30.65341967 -0.79884463*x1 -4.12128048*x2 + 6.23015952*x3 + 9.97751475*x4
    return(y1, y2, y3)

In [71]:
logit = reg(x11, x22, x33, x44)

In [74]:
logit

(array([-15.5768802 ,   7.05365249,   8.21476647, -11.10510531,
        -10.31788601,  -8.28864486, -18.76858986, -12.34944312,
        -15.96660997,   8.92825034,   8.81009157, -13.04155668,
          7.50990015,  -4.35452223,   7.98604985, -12.76549027,
        -15.33712936, -10.21076145,  -9.71477798, -15.13608465,
        -19.06760861,   7.60398926, -10.18472677, -13.45975084,
         -9.05241508, -11.24621642,  -3.08303241, -17.95791137,
          6.60777337, -14.63456595,   7.31506939,   8.23218359,
         -8.89812274,  -8.87776906, -20.73254419, -16.96299481,
          8.7863046 ,   6.32240054,   7.33637145, -11.61085989,
        -17.93919492, -13.82551164, -11.78912121,   7.63037489,
          7.26849903]),
 array([-2.34002036, -3.91077335, -1.88670099,  1.61184569, -1.4277701 ,
        -0.71724119,  1.09689461,  0.82328684, -0.1578983 , -4.70715789,
        -5.85447752, -0.83693114, -0.20104112,  1.51091119, -1.15953829,
        -0.51222128, -3.38236296,  0.03472943, -0.803

In [72]:
oz = np.exp(reg(x11, x22, x33, x44))

In [73]:
oz

array([[1.71809386e-07, 1.15707725e+03, 3.69511320e+03, 1.50353674e-05,
        3.30368813e-05, 2.51354854e-04, 7.06163054e-09, 4.33216509e-06,
        1.16356164e-07, 7.54205782e+03, 6.70153290e+03, 2.16832261e-06,
        1.82603121e+03, 1.28485768e-02, 2.93966188e+03, 2.85770910e-06,
        2.18358123e-07, 3.67724568e-05, 6.03845080e-05, 2.66981987e-07,
        5.23652037e-09, 2.00618313e+03, 3.77423871e-05, 1.42726456e-06,
        1.17107870e-04, 1.30566050e-05, 4.58201005e-02, 1.58846696e-08,
        7.40831621e+02, 4.40847885e-07, 1.50277608e+03, 3.76003517e+03,
        1.36645205e-04, 1.39454935e-04, 9.90764556e-10, 4.29600679e-08,
        6.54400471e+03, 5.56908271e+02, 1.53513170e+03, 9.06708360e-06,
        1.61847740e-08, 9.90048763e-07, 7.58664411e-06, 2.05982208e+03,
        1.43439585e+03],
       [9.63256768e-02, 2.00250087e-02, 1.51571020e-01, 5.01205342e+00,
        2.39843153e-01, 4.88096968e-01, 2.99485140e+00, 2.27797487e+00,
        8.53936619e-01, 9.03040654e-03,

In [15]:
X_train.head(1)

sepal_length  sepal_width  petal_length  petal_width
33           5.5          4.2           1.4          0.2

In [16]:
reg(5.5, 4.2, 1.4, 0.2) # 로짓 반환

(9.394314200000004, -4.718412539000001, -41.63871687300001)

In [17]:
import numpy as np
np.exp(reg(5.5, 4.2, 1.4, 0.2)) # 오즈비

array([1.20198436e+04, 8.92934229e-03, 8.25154037e-19])

In [18]:
# 오즈비를 원래 특정 클래스일 확률로 반환
from sympy import Symbol, solve
x = Symbol('x')
e = x/(1-x)-1.20198436e+04
solve(e) # 0일 확률

[0.999916811162904]

In [19]:
e = x/(1-x)-8.92934229e-03
solve(e) # 1일 확률

[0.00885031479977852]

In [20]:
e = x/(1-x)-8.25154037e-19
solve(e) # 2일 확률

[8.25154037000000e-19]

In [21]:
## test에도 적용
X_test.head(1)

sepal_length  sepal_width  petal_length  petal_width
148           6.2          3.4           5.4          2.3

In [22]:
reg(6.2, 3.4, 5.4, 2.3) # 로짓 반환

(-15.576880196000003, -2.340020361999998, 6.972535324999992)

In [23]:
np.exp(reg(6.2, 3.4, 5.4, 2.3)) # 오즈비

array([1.71809386e-07, 9.63256768e-02, 1.06692432e+03])

In [24]:
# 오즈비를 원래 특정 클래스일 확률로 반환
from sympy import Symbol, solve
x = Symbol('x')
e = x/(1-x)-1.71809386e-07
solve(e) # 0일 확률

[1.71809356481540e-7]

In [25]:
e = x/(1-x)-9.63256768e-02
solve(e) # 1일 확률

[0.0878622829314363]

In [26]:
e = x/(1-x)-1.06692432e+03
solve(e) # 2일 확률

[0.999063604057636]

In [27]:
model.n_iter_ # 모든 클래스의 실제 반복 횟수(최대 반복 횟수)

array([27, 35, 48])

In [28]:
# 클래스에 속할 확률 반환. (시그모이드 함수를 적용해 계산한 확률)
model.predict_proba(X_test) # 각각 0, 1, 2일 확률임. 

array([[1.58069040e-07, 8.08355630e-02, 9.19164279e-01],
       [9.80729791e-01, 1.92702092e-02, 1.44032616e-16],
       [8.83660214e-01, 1.16339786e-01, 1.09742723e-16],
       [1.10125474e-05, 6.10622960e-01, 3.89366027e-01],
       [1.69869263e-04, 9.94696666e-01, 5.13346497e-03],
       [7.65303285e-04, 9.98919084e-01, 3.15612351e-04],
       [4.03691928e-09, 4.28567973e-01, 5.71432023e-01],
       [5.07742209e-06, 8.14485670e-01, 1.85509252e-01],
       [8.00002036e-08, 3.16688640e-01, 6.83311280e-01],
       [9.91128631e-01, 8.87136898e-03, 1.20346744e-17],
       [9.97148889e-01, 2.85111127e-03, 4.21901923e-18],
       [2.28924732e-06, 3.19034489e-01, 6.80963222e-01],
       [6.89581599e-01, 3.10418401e-01, 2.90930891e-16],
       [1.52492478e-02, 9.84749671e-01, 1.08088826e-06],
       [8.07211691e-01, 1.92788309e-01, 8.42868808e-17],
       [7.18717065e-06, 9.42309349e-01, 5.76834635e-02],
       [2.12044592e-07, 3.19013917e-02, 9.68098396e-01],
       [7.07371228e-05, 9.78558

In [29]:
c = model.predict_proba(X_test)

In [30]:
import pandas as pd
c_df = pd.DataFrame(c, columns=list('123'))

In [31]:
c_df['sum'] = c_df['1'] + c_df['2'] + c_df['3']

In [32]:
c_df['pred'] = [np.argmax(line) for line in np.array(c)]

In [33]:
c_df.head()

1         2             3  sum  pred
0  1.580690e-07  0.080836  9.191643e-01  1.0     2
1  9.807298e-01  0.019270  1.440326e-16  1.0     0
2  8.836602e-01  0.116340  1.097427e-16  1.0     0
3  1.101255e-05  0.610623  3.893660e-01  1.0     1
4  1.698693e-04  0.994697  5.133465e-03  1.0     1

In [34]:
ovr_pred= model.predict(X_test) # target으로는 똑같이 argmax 값을 반환함.
ovr_pred

array([2, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0,
       0])

## Multinomial - softmax
- 로지스틱은 여러개의 이진분류기를 연결하는 것과 더불어, 직접 다중클래스를 지원함. 
- 이를 소프트맥스 회귀 / 다항 로지스틱 회귀라고 함. 

### Process
소프트맥스 회귀모델이 각 클래스 k에 대한 **점수를 계산**하고, 그 점수에 **소프트맥스 함수**를 적용해 각 클래스의 확률을 추정한 후 가장 높은 확률 선택.    
> 1) 점수를 계산하는 식은 선형 회귀 예측식과 비슷한데, 각 클래스마다 자신만의 **파라미터 벡터**가 있고, 샘플 X에 대해 선형으로 결합되어 있음. (회귀랑 똑같음)    
> 2) 이 점수를 소프트맥스 함수에 통과시켜 각 클래스 확률을 추정함.      
> 3) 이러한 추정확률이 가장 높은 클래스를 선택함.    
>> **Sortmax 함수** : 각 점수에 exp를 취한 후, 정규화함(모든 지수함수 결과의 합으로 나눔)       


In [35]:
# Logistic regression
import warnings
warnings.filterwarnings('ignore')

from sklearn.linear_model import LogisticRegression
Logit = LogisticRegression(C=1e2, random_state=1, multi_class='multinomial') 
model=Logit.fit(X_train, y_train)
y_train_pred = Logit.predict(X_train)
y_test_pred = Logit.predict(X_test)

In [36]:
model.coef_ # 각 클래스에 대한 점수를 계산함. (회귀식과 비슷)

array([[-0.12719837,  2.25944687, -6.18925133, -3.38970816],
       [ 0.56950349,  1.12009438, -0.14751722, -3.61616035],
       [-0.44230512, -3.37954125,  6.33676855,  7.00586852]])

In [37]:
model.intercept_

array([ 20.99972641,   4.79543305, -25.79515947])

In [38]:
def score(x1, x2, x3, x4):
    y1 = 20.99972641 -0.12719837*x1 + 2.25944687*x2 -6.18925133*x3  -3.38970816*x4
    y2 = 4.79543305 +0.56950349*x1 + 1.12009438*x2 -0.14751722*x3 -3.61616035*x4
    y3 = -25.79515947 -0.44230512*x1 -3.37954125*x2 +6.33676855*x3 +7.00586852*x4
    return(y1, y2, y3)

In [39]:
X_test.head(1)

sepal_length  sepal_width  petal_length  petal_width
148           6.2          3.4           5.4          2.3

In [40]:
score(6.2, 3.4, 5.4, 2.3) # 각 클래스에 대한 score

(-13.325070076000003, 3.0209137869999996, 10.304156302000006)

In [41]:
# 이들을 softmax에 통과시킴. 
np.exp(score(6.2, 3.4, 5.4, 2.3))

array([1.63303538e-06, 2.05100249e+01, 2.98564538e+04])

In [42]:
# softmax 식 직접 구현 
np.exp(score(6.2, 3.4, 5.4, 2.3))/(1.63303538e-06 + 2.05100249e+01 + 2.98564538e+04)

array([5.46586793e-11, 6.86482905e-04, 9.99313516e-01])

In [43]:
model.n_iter_

array([100])

In [44]:
model.predict_proba(X_test) 
# 각 클래스에 softmax를 적용한 확률값 도출. 
# 정규화의 효과로 row별 각 클래스의 합은 1이 나옴. 

array([[5.46586752e-11, 6.86482851e-04, 9.99313517e-01],
       [9.98776983e-01, 1.22301679e-03, 2.75778165e-20],
       [9.99793039e-01, 2.06961419e-04, 4.91476679e-21],
       [5.55580351e-06, 3.91931500e-01, 6.08062944e-01],
       [1.30970452e-05, 9.99354753e-01, 6.32150027e-04],
       [1.61957236e-04, 9.99771393e-01, 6.66501836e-05],
       [4.82554481e-13, 3.00515629e-04, 9.99699484e-01],
       [3.26458832e-06, 8.38979511e-01, 1.61017224e-01],
       [2.50520538e-10, 4.80450254e-03, 9.95195497e-01],
       [9.99890766e-01, 1.09234478e-04, 1.84098980e-22],
       [9.99745059e-01, 2.54941001e-04, 1.22303506e-22],
       [3.44178464e-07, 3.47256418e-01, 6.52743238e-01],
       [9.99674489e-01, 3.25510561e-04, 3.10340027e-20],
       [1.49737334e-02, 9.85025676e-01, 5.90382135e-07],
       [9.99734135e-01, 2.65865141e-04, 5.36783865e-21],
       [7.96337873e-07, 9.83282017e-01, 1.67171867e-02],
       [5.36975368e-10, 2.52350058e-03, 9.97476499e-01],
       [1.45648536e-05, 9.90451

In [45]:
b = model.predict_proba(X_test) 

In [46]:
import pandas as pd
import numpy as np
b_df= pd.DataFrame(b, columns=list('123'))

In [47]:
b_df['sum'] = b_df['1'] + b_df['2'] + b_df['3']

In [48]:
b_df['pred'] = [np.argmax(line) for line in np.array(b)]

In [49]:
b_df.head() # 각 클래스의 최대 확률 값을 target으로 반환함. 

1         2             3  sum  pred
0  5.465868e-11  0.000686  9.993135e-01  1.0     2
1  9.987770e-01  0.001223  2.757782e-20  1.0     0
2  9.997930e-01  0.000207  4.914767e-21  1.0     0
3  5.555804e-06  0.391931  6.080629e-01  1.0     2
4  1.309705e-05  0.999355  6.321500e-04  1.0     1

In [50]:
multi_pred = model.predict(X_test)
multi_pred

array([2, 0, 0, 2, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0,
       0])

## 성능 비교

In [53]:
print(ovr_pred)
print(multi_pred)

[2 0 0 1 1 1 2 1 2 0 0 2 0 1 0 1 2 1 1 2 2 0 1 2 1 1 1 2 0 2 0 0 1 1 2 2 0
 0 0 1 2 2 1 0 0]
[2 0 0 2 1 1 2 1 2 0 0 2 0 1 0 1 2 1 1 2 2 0 1 2 1 1 1 2 0 2 0 0 1 1 2 2 0
 0 0 1 2 2 1 0 0]


In [61]:
from sklearn.metrics import accuracy_score, confusion_matrix
print('ovr_accuracy = ', str(accuracy_score(y_test, ovr_pred)))
print('multi_accuracy = ', str(accuracy_score(y_test, multi_pred)))

ovr_accuracy =  0.9777777777777777
multi_accuracy =  1.0


In [62]:
print('ovr_score = ', str(confusion_matrix(y_test, ovr_pred)))
print('multi_score = ', str(confusion_matrix(y_test, multi_pred)))

ovr_score =  [[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]
multi_score =  [[15  0  0]
 [ 0 15  0]
 [ 0  0 15]]
